\connect twentyeyesdb zaphod
INSERT INTO web.posts (post_id, title, post, date_added, current_or_nah)
VALUES (DEFAULT, '20eyes upgrade!', 'After reading a ton about Docker late one night before an early work day so obviously I didn''t finish restoring the previous workflow I had using Jenkins to deploy this stuff to a production server. LESSONS LEARNED: Have a plan! I really should have known this wasn''t as simple as backing up my old config and system files. If I had taken the time to write down what I wanted, and the absolute minimum things required to get it running, things would have run a whole lot smoother. Don''t be scared! I avoided this upgrade for a while because I was making too big of a deal about going dark for a little. The upgrade process is a process I''ve done several times on local machines, doing it on a remote server was no different at all. Jenkins rules! I''m fortunate enough at work to be able to use Atlassian tools, but I think considering my past experiences with Jenkins, I''ve grown to be somewhat partial to it. Bamboo is a phenomenal tool, but I will always pick Jenkins given the choice between the two.Whoa, Docker.. My original plan was to drop a few containers on here to see exactly how portable thye are. It definitely isn''t as easy as I assumed it would be, but actually gets more and more interesting the more I learn about it. More to come from this for sure. IN OTHER NEWS! Etsy engineers Daniel Schauenberg and Ryan Frantz are coming to DC next month to speak about their engineering practices at Etsy and I am beyond stoked!! I got a new bike', DEFAULT, DEFAULT);

INSERT INTO web.posts (post_id, title, post, date_added, current_or_nah)
VALUES (DEFAULT, 'Jenkins & I.. RUNITED!', 'One of my favorite developers left the company I work to persue a new job, good for him! He was one of the few people left who were passionate about changing the course of our tech team from relying on manual testing, and was supporting almost all of the test infrastructure on his own. I won''t go in to great deal of said ''test infrastructure'' since it''s not that much to speak of, but the most glaring issue was that no one would be supporting Bamboo with him leaving. I have worked with Bamboo a little bit before but I was always turned off by their shifty community of plugins (don''t get me started), plus the license was about to expire for our Bamboo install. How fortuitous! I have been using Jenkins for a while now so I saw this as my chance to get us to ditch Bamboo and start fresh with Jenkins. I was like a kid in a candy store after setting up the fresh install, grabbing every plugin I could imagine being remotely useful for us, or even if it wasn''t that useful it would be interesting to look at. This Bamboo > Jenkins switch started about a month ago, and as of last week it looks like we''re fully migrated over to Jenkins and even have the test pipeline looking better than it did before! Great success! Besides all the fun of playing with shiny new toys, work has been getting somewhat trying. The senior QA engineer quit to persue a different job (good for him as well!) which left quality assurance in a very dubious state. This was basically a breaking point for me, I hadn''t been incredibly satisfied with my job in the past few months due to an huge spike in manual testing and time for creating very basic pieces of an automated testing framework was thrown out the window. A pile of meetings and conversations later we''ve finally convinced management that the value of manual testing may seem better from a very narrow view, in the long run it will cost us in technical debt, and possibly more employee exits. So for now we''ve been aforded a little bit of extra time to work on it. It''s a small victory in my opinion, allowing me time to work on getting our tech team some better tools to work with is a step in the right direction but, the entire tech team needs to commit to this not as a pet project but as a project vital to our company staying in the modern era of software development. I don''t want to overload this post, will continue it in a few days!', DEFAULT, DEFAULT);

INSERT INTO web.posts (post_id, title, post, date_added, current_or_nah)
VALUES (DEFAULT, 'Hound Search 2: Son of hound search, and other updates!', 'What a week. First off, I added a very adorable little script to my post Jenkins web build that initiates a git pull for all of the repos that are searchable within hound. I tried to change the css but that turned out horribly so original css remains! Eventually I''m going to create a separate jenkins job for this and trigger a pull when any repo gets a commit to master. If you''d like to take a look at the script you can on my github page. Work related I finally found a really good, very concise ruby gem to write our QA chat bot called xmpp4r-robot owner about it and he mentioned he may not have the time to work on it personally, but will definitely accept pull requests. I think I''m going to do it, the MUC library for XMPP4R doesn''t seem THAT bad. Only a few very minor tweaks to Rundeck and I think I can shift in to only supporting the system and no longer actively adding or testing jobs. I''m sure that sooner or later there will be more tasks to add. **Edit: Pretty sure Hound already initiates a pull on a scheduled basis, rendering that little script I wrote pretty worthless, but fun to write all the same!', DEFAULT, DEFAULT);

INSERT INTO web.posts (post_id, title, post, date_added, current_or_nah)
VALUES (DEFAULT, 'twenty eyes dot org: son of 20eyes!', 'Hello there! Since moving over to digital ocean for my web/utility VMs I''ve had a few upgrades. I''m currently collecting and indexing all my system logs and apache logs on cthulhu (VM1). Hastur is the second VM which does most of the behind the scenes work and is also running my jenkins instance. Eventually I''ll add in a section to query live site metrics from elasticsearch. In bigger news, I''ve got a working alpha version of my new and improved version of this page using  %a{:href => ''http://http://www.sinatrarb.com/'', :target => ''_blank''} Sinatra and  %a{:href => ''http://getbootstrap.com/'', :target => ''_blank''} Bootstrap. I''ve still got some tweaking to do but it''s a first step towards making this page a little more mobile friendly and visually appealing. I don''t have to stomach to go full geocities so I''ll just move up to the late 2000''s B-)', DEFAULT, DEFAULT);

INSERT INTO web.posts (post_id, title, post, date_added, current_or_nah)
VALUES (DEFAULT, 'I''m moving EVERYTHING!', 'Well Looks like I''ll be moving to NYC on July 31st, very excited for that! I''m also ditching rackspace to go with Digital Ocean. I''m ditching rackspace because Digital Ocean is way cheaper I get double the RAM rackspace was giving me BYE FELICIARACKSPACE. I''ve been experiencing crazy amounts of burnout at work and it''s beggining to really effect my free time. Typically on the weekend I usually try checking out new tools I''ve read about during the week or continue work on ongoing projects, but lately I just haven''t felt like doing it. I''ve decided to put the breaks on doing work stuff during non work hours for the time being. I''ve been slowly getting back in to ruby and working a lot on TDD using test-unit', DEFAULT, DEFAULT);

INSERT INTO web.posts (post_id, title, post, date_added, current_or_nah)
VALUES (DEFAULT, 'navbar.. more like navBORING amirite?!', 'So my update to this website is essentially done except the dang hamburger button won''t open when the browser drops to mobile size. Needless to say I''ve been smashing my head against my keyboard for a little while now and the fix still escapes me. I''m almost certain the issue is a js file not being read properly, but I''ll have to investigate more another time, since I don''t want to take up my whole Sunday fiddling with a hamburger button! In other news, I made an about me page,  %a{:href => ''/about_me''} check it out!', DEFAULT, DEFAULT);

INSERT INTO web.posts (post_id, title, post, date_added, current_or_nah)
VALUES (DEFAULT, 'NEW SITE IS GO!', 'Finally, the navigation bar is working as it should on the sinatra / ruby / haml version of this site and I''m ready to retire the old one. I''m moving to NYC at the end of this week and welcome this fix amid being SO stressed out. But the end is approaching and I can''t wait to be settled in and start my new adventure in New York', DEFAULT, 'true');
