# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30e72a0d3ab098659574723dbad55a4eb2f31135f260054eab6121de0651123ac55b152ae27581bc36e4958599ae68612eb12793f88f07268338150d4a9b4b55

test:
  secret_key_base: f0de863ac1ed5ed210ee56ba481e092e91be661bb7744eb474f12e9e42fc88a226be5d7bc540fabe2dc49547b10da174501d6ae4d3492bbf119d57fcd5c31fad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
